version: '3'

# All Services
services:
  # Service mysql
  mysql:
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT_EXPOSED}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "${MYSQL_VOLUME_DATA}:/var/lib/mysql"
    container_name: magento2_mysql
    networks:
      magento2_aissyass:
        ipv4_address: "${MYSQL_IP_INTERNE}"

  # Service phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT_EXPOSED}:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT_EXPOSED}
    container_name: magento2_phpmyadmin
    networks:
      magento2_aissyass:
        ipv4_address: "${PHPMYADMIN_IP_INTERNE}"

  #Service apache2
  apache2:
    image: yaissaoui/magento2:2.2.x
    ports:
      - 80:80
      - 10000:10000
      - 443:443
    links:
      - mysql
    volumes:
      - "${WEB_VOLUME_HTML}:/var/www/html"
      - "${LOG_VOLUME_DATA}:/var/log/apache2"
    container_name: magento2_apache2
    networks:
      magento2_aissyass:
        ipv4_address: "${WEB_IP_INTERNE}"

# Networks
networks: 
  magento2_aissyass:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: "${NETWORK_SUBNET}"